---
name: Release the Project

on:
  workflow_dispatch:

permissions: read-all

jobs:
  Super-Linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout The Repository
        uses: actions/checkout@v4 # complete the file
...